name: SonarQube Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read  # Needed for PR decoration

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    env: # Define environment variables for the entire job
      BUNDLE_RUBYGEMS__PKG__GITHUB__COM: "y2kstack:${{ secrets.MY_PAT }}"

    steps:

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true # This will now use the job-level BUNDLE_ variable for authentication
      
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # If your project needs Ruby (remove if not needed)
      # - name: Set up Ruby
      #   uses: ruby/setup-ruby@v1
      #   with:
      #     ruby-version: '3.0'

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=git-test-jp
