name: Test Project with Struct Definer
on:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Updated to latest version for better compatibility
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - name: Configure GitHub Packages authentication
        run: |
          bundle config rubygems.pkg.github.com/y2kstack y2kstack:${{ secrets.PAT }}
      - name: Install dependencies
        run: |
          bundle install
      - name: Run tests
        run: |
          bundle exec ruby test.rb
