name: Test Project with Struct Definer
on:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true # Enable caching for faster runs
      - name: Configure GitHub Packages authentication
        env:
          BUNDLE_RUBYGEMS__PKG__GITHUB__COM: y2kstack:${{ secrets.MY_PAT }}
        run: |
          bundle config set --global rubygems.pkg.github.com/y2kstack "$BUNDLE_RUBYGEMS__PKG__GITHUB__COM"
      - name: Install dependencies
        run: |
          bundle install
      - name: Run tests
        run: |
          bundle exec ruby test.rb
