name: Test Project with Struct Definer
on:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure GitHub Packages authentication
        env:
          BUNDLE_RUBYGEMS__PKG__GITHUB__COM: y2kstack:${{ secrets.MY_PAT }}
        run: |
          bundle config set --global rubygems.pkg.github.com "$BUNDLE_RUBYGEMS__PKG__GITHUB__COM"
      - name: Debug bundle config
        run: |
          bundle config list
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: false # Disabled to avoid premature bundle commands
      - name: Configure bundle path
        run: |
          bundle config --local path /home/runner/work/my-test-project/my-test-project/vendor/bundle
      - name: Update Gemfile.lock
        run: |
          bundle lock
      - name: Install dependencies
        run: |
          bundle install
      - name: Run tests
        run: |
          bundle exec ruby test.rb
